package com.ducks.synaptra.client.openai.data;

/**
 * Represents a function call generated by the model within a {@link ToolCall}.
 *
 * <p>The {@code arguments} field is a JSON-encoded string that must be parsed into a
 * domain-specific object before executing the function in your backend.
 *
 * @param name Name of the function the model requested to call.
 * @param arguments JSON string of the serialized argument object.
 * @author Leandro Marques
 * @since 1.0.0
 */
public record FunctionCall(String name, String arguments) {}
